task:
  name: Run inference on
  only_if: "changesInclude('ai/**', '.cirrus.yml')"
  matrix:
    arm_container:
      image: docker.io/openeuler/openeuler:22.03
      cpu: 4
      memory: 4G
    container:
      image: docker.io/openeuler/openeuler:22.03
      cpu: 4
      memory: 4G
#    persistent_worker:
#      labels:
#        provider: huaweicloud
  env_script: |
    uname -a
    cat /etc/os-release
  setup_script: |
    if [[ -x "$(command -v dnf)" ]]
    then
      dnf install -y python3 python3-pip curl tar
    fi
    pip3 install onnxruntime pillow matplotlib
    curl https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v2/resnet50v2.tar.gz -o resnet50v2.tar.gz 
    tar xvzf resnet50v2.tar.gz --warning=no-unknown-keyword -C ai/inference/resnet50/
    curl https://media.githubusercontent.com/media/onnx/models/main/validated/vision/object_detection_segmentation/yolov3/model/yolov3-12.onnx --create-dirs -o ai/inference/yolo/yolov3/yolov3.onnx
    curl https://media.githubusercontent.com/media/onnx/models/main/validated/text/machine_comprehension/bert-squad/model/bertsquad-12.onnx --create-dirs -o ai/inference/bert/bert-qa/bertsquad-12.onnx
    echo "checking pull request #${CIRRUS_PR}"
  resnet50_script: |
    cd ai/inference/resnet50/
    python3 resnet50_modelzoo_onnxruntime_inference.py
  yolov3_script: |
    cd ai/inference/yolo/
    python3 yoloV3_object_detection_onnxruntime_inference.py
  bert_script: |
    cd ai/inference/bert/
    python3 bert_qa_onnxruntime_inference.py
