task:
  name: Run inference on
#  only_if: "changesIncludeOnly('ai/*')"
  matrix:
    arm_container:
      image: docker.io/openeuler/openeuler
    container:
      image: docker.io/library/rockylinux:9
  env_script: |
    uname -a
    cat /etc/os-release
  setup_script: |
    if [[ -x "$(command -v dnf)" ]]
    then
      dnf install -y python3 python3-pip
    fi
    pip3 install onnxruntime
  script: |
    echo "checking pull request #${CIRRUS_PR}"
