apiVersion: v1
kind: Pod
metadata:
  name: nested-pod
spec:
  volumes:
  - name: os-version-checker-storage
    emptyDir: {}
  initContainers:
  - name: os-version-checker-init
    image: dockerhub.ultimum.io/ultimum-internal/os-version-checker:latest
    volumeMounts:
      - name: os-version-checker-storage
        mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cp -a /opt/app/* /tmp"]
  containers:
  - name: os-version-checker
    image: dockerhub.ultimum.io/ultimum-internal/os-version-checker:latest
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cat"]
    tty: true
  - name: debian-binary-base_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-base:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-base jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-openvswitch-vswitchd_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-openvswitch-vswitchd:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-openvswitch-vswitchd jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-openstack-base_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-openstack-base:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-openstack-base jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-nova-libvirt_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-nova-libvirt:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-nova-libvirt jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-aodh-base_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-aodh-base:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-aodh-base jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-aodh-expirer_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-aodh-expirer:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-aodh-expirer jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-aodh-notifier_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-aodh-notifier:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-aodh-notifier jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-octavia-base_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-octavia-base:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-octavia-base jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-aodh-api_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-aodh-api:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-aodh-api jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-neutron-base_jajo-test-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-neutron-base:jajo-test-ussuri
    volumeMounts:
    - name: os-version-checker-storage
      mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-neutron-base jajo-test-ussuri; cat"]
    tty: true
  - name: debian-binary-freezer-api_kevko-stein
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-freezer-api:kevko-stein
    volumeMounts:
      - name: os-version-checker-storage
        mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-freezer-api kevko-stein; cat"]
    tty: true
  - name: debian-source-base_kevko-stein
    image: dockerhub.ultimum.io/kolla-dev/debian-source-base:kevko-stein
    volumeMounts:
      - name: os-version-checker-storage
        mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-source-base kevko-stein; cat"]
    tty: true
  - name: debian-binary-base_kevko-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-source-base:kevko-ussuri
    volumeMounts:
      - name: os-version-checker-storage
        mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-source-base kevko-ussuri; cat"]
    tty: true
  - name: debian-binary-redis-base_kevko-ussuri
    image: dockerhub.ultimum.io/kolla-dev/debian-binary-redis-base:kevko-ussuri
    volumeMounts:
      - name: os-version-checker-storage
        mountPath: /tmp
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "cd /tmp; ./get_image_versions.sh debian-binary-redis-base kevko-ussuri; cat"]
    tty: true

