name: CI Gate

on:
  pull_request:
    # Runs on any pull request to main
    branches: [ main ]
    # AI directory apply .cirrus.yml to test
    paths-ignore:
      - 'ai/**'
      - '.cirrus.yml'

  workflow_dispatch:

jobs:
  check-on-x86-64:
    env:
      check-input: "\
          yoga/dev-Mainline,\
          wallaby/dev-22.03-LTS-Next,\
          train/dev-22.03-LTS-Next,\
          wallaby/22.03-LTS,\
          train/22.03-LTS,\
          train/20.03-LTS-SP3,\
          rocky/20.03-LTS-SP3,\
          queens/20.03-LTS-SP3,\
          wallaby/21.09,\
          victoria/21.03,\
          train/dev-20.03-LTS-SP3,\
          "
    outputs:
      check-input: ${{ env.check-input }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        container-image: ['docker.io/openeuler/openeuler']
        arch: ['x86_64']
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container-image }}
    name: Test it on ${{ matrix.container-image }} ${{ matrix.arch }} with python3
    steps:
      - uses: actions/checkout@v3
      - name: Env
        run: |
          uname -a
          cat /etc/os-release
      - name: Setup
        run: |
          dnf install -y python3 python3-pip file grep
          pip3 install -r requirements.txt
      - name: Lint
        run: |
          pip3 install flake8
          flake8 --count .
      - name: Run
        run: |
          python3 VersionStatus.py -n docs/index.html -r ${{ env.check-input }}
          file docs/index.html
          output=$(grep 'view_window' docs/index.html)
          echo $output
  check-on-arm64:
    needs: check-on-x86-64
    strategy:
      matrix:
        os: [ubuntu22.04]
        arch: ['aarch64']
    runs-on: ubuntu-22.04
    name: Test it on ${{ matrix.os }} ${{ matrix.arch }} with python3
    steps:
      - uses: actions/checkout@v3
      # TODO(ChenRui): run-on-arch-action will support openEuler in 3.0.0
      # refactor this job when it's available.
      # https://github.com/uraimo/run-on-arch-action/pull/89
      - uses: uraimo/run-on-arch-action@v2.3.0
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.os }}
          githubToken: ${{ github.token }}
          install: |
            uname -a
            cat /etc/os-release
            apt-get update -q -y
            apt-get install -q -y python3 python3-pip file grep
          run: |
            pip3 install -r requirements.txt
            python3 VersionStatus.py -n docs/index.html -r ${{ needs.check-on-x86-64.outputs.check-input }}
            file docs/index.html
            output=$(grep 'view_window' docs/index.html)
            echo $output
