name: CI gate

on:
  pull_request:
    # Runs on any pull request to main
    branches: [ main ]

  workflow_dispatch:

jobs:
  check-on-x86-64:
    env:
      check-input: "\
          train/dev-22.03-LTS-Next,\
          train/20.03-LTS-SP3,\
          rocky/20.03-LTS-SP2,\
          queens/20.03-LTS-SP2,\
          wallaby/21.09,\
          victoria/21.03,\
          train/dev-20.03-LTS-Next,\
          train/dev-20.03-LTS-SP3,\
          train/dev-20.03-LTS-SP1,\
          train/dev-21.09,\
          "
    outputs:
      check-input: ${{ env.check-input }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        arch: ['x86_64']
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    name: Test it on ${{ matrix.os }} ${{ matrix.arch }} with python${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --count .
      - name: Run
        # Run tool, then check file and content
        run: |
          python VersionStatus.py -n docs/index.html -r ${{ env.check-input }}
          file docs/index.html
          output=$(grep 'releases.openstack.org' docs/index.html)
          echo $output | grep 'victoria'
          echo $output | grep 'wallaby'
          echo $output | grep 'queens'
          echo $output | grep 'rocky'
          echo $output | grep 'train'
  check-on-arm64:
    needs: check-on-x86-64
    strategy:
      matrix:
        os: [ubuntu20.04]
        arch: ['aarch64']
    runs-on: ubuntu-20.04
    name: Test it on ${{ matrix.os }} ${{ matrix.arch }} with python3
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.os }}
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y python3-minimal python3-pip
          run: |
            pip3 install -r requirements.txt
            pip3 install flake8
            flake8 --count .
            python3 VersionStatus.py -n docs/index.html -r ${{ needs.check-on-x86-64.outputs.check-input }}
            file docs/index.html
            output=$(grep 'releases.openstack.org' docs/index.html)
            echo $output | grep -A 5 "URI:"
