name: CI Gate

on:
  pull_request:
    # Runs on any pull request to main
    branches: [ main ]
    # AI directory apply .cirrus.yml to test
    paths-ignore:
      - 'ai/**'
      - '.cirrus.yml'

  workflow_dispatch:

jobs:
  check:
    env:
      check-input: "\
          25.03/antelope,\
          24.03-LTS-SP1/wallaby,\
          24.03-LTS-SP1/antelope,\
          24.03-LTS/wallaby,\
          24.03-LTS/antelope,\
          22.09/yoga,\
          22.03-LTS-SP4/train,\
          22.03-LTS-SP4/wallaby,\
          22.03-LTS-SP3/train,\
          22.03-LTS-SP3/wallaby,\
          21.09/wallaby,\
          21.03/victoria,\
          20.03-LTS-SP4/queens,\
          20.03-LTS-SP4/rocky,\
          20.03-LTS-SP4/train,\
          dev-24.03-LTS-Next/wallaby,\
          dev-24.03-LTS-Next/antelope,\
          "
    outputs:
      check-input: ${{ env.check-input }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        container-image: ['quay.io/openeuler/openeuler:24.03-lts-sp1']
    runs-on: ${{ matrix.os }}
#    container: ${{ matrix.container-image }}
    name: Test in container ${{ matrix.container-image }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Env
        run: |
          uname -a
          cat /etc/os-release
          python --version
          pip --version
      - name: Flake8
        run: |
          pip install flake8
          flake8 --count VersionStatus.py
      - name: Run
        run: |
          pip install -r requirements.txt
          python VersionStatus.py -n docs/index.html -r ${{ env.check-input }}
          file docs/index.html
          output=$(grep 'view_window' docs/index.html)
          echo $output
