name: CI

on:
  pull_request:
    # Runs on any pull request to main
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ['3.8', '3.x', 'pypy-3.8']
    runs-on: ${{ matrix.os }}
    name: Test it with python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --count .
      - name: Run
        # Run tool, then check file and content
        run: |
          python VersionStatus.py -r victoria/21.03,wallaby/21.09,queens/20.03-LTS-SP2,rocky/20.03-LTS-SP2 -n docs/index.html
          file docs/index.html
          output=$(grep 'releases.openstack.org' docs/index.html)
          echo $output | grep 'victoria'
          echo $output | grep 'wallaby'
          echo $output | grep 'queens'
          echo $output | grep 'rocky'
