name: Publish OS Version Checker Page

on:
  push:
    paths:
      - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/**'
    branches: [ main ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and publish
      run: |
        export GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        python VersionStatus.py -r victoria-21.03,train-ussuri,train-20.03-LTS-SP1 -n pages/index.html
        git add index.html
        git commit -m "update os-version-check index.html"
        git push
