name: Publish Page

on:
  push:
    # Runs on any change be merged to main
    branches: [ main ]
    # AI directory apply .cirrus.yml to test
    paths-ignore:
      - 'ai/**'
      - '.cirrus.yml'
  schedule:
    # Runs at 00:00 UTC (8:00 AM Beijing) every day
    - cron:  '0 0 * * *'

jobs:
  publish:
    env:
      publish-input: "\
          25.03/antelope,\
          24.03-LTS-SP1/wallaby,\
          24.03-LTS-SP1/antelope,\
          24.03-LTS/wallaby,\
          24.03-LTS/antelope,\
          22.09/yoga,\
          22.03-LTS-SP4/train,\
          22.03-LTS-SP4/wallaby,\
          22.03-LTS-SP3/train,\
          22.03-LTS-SP3/wallaby,\
          21.09/wallaby,\
          21.03/victoria,\
          20.03-LTS-SP4/queens,\
          20.03-LTS-SP4/rocky,\
          20.03-LTS-SP4/train,\
          dev-24.03-LTS-Next/wallaby,\
          dev-24.03-LTS-Next/antelope,\
          "
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Env
        run: |
          uname -a
          cat /etc/os-release
          python --version
          pip --version
      - name: Generate OS Version Checker Page
        run: |
          pip install -r requirements.txt
          python VersionStatus.py -n docs/index.html -r ${{ env.publish-input }}
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
