name: Publish Page

on:
  push:
    # Runs on any change be merged to main
    branches: [ main ]
  schedule:
    # Runs at 00:00 UTC (8:00 AM Beijing) every day
    - cron:  '0 0 * * *'

jobs:
  publish:
    env:
      publish-input: "\
        train/dev-22.03-LTS-Next,\
        train/20.03-LTS-SP3,\
        rocky/20.03-LTS-SP2,\
        queens/20.03-LTS-SP2,\
        wallaby/21.09,\
        victoria/21.03,\
        "
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate OS Version Checker Page
        run: |
          python VersionStatus.py -n docs/index.html -r ${{ env.publish-input }}
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: ${{ github.event.head_commit.message }}
